### ISSUE TITLE
String quotation

### ISSUE THREAD

**Issue by lezsakdomi** [petrzjunior/odata-filter-to-ast#3]
The OData specification mandates string literal quotation using `'`, but this repo uses `"` for literal quotation. OData uses `"` for identifier quotation.

I'd introduce an issue or PR to make this library OData conformant, but it would break all the dependent projects.

Maybe after increasing the major version? Maybe just adding a warning to the readme? Maybe supporting both for string literals, and not supporting quoted identifiers?

I suspect that there are more inconsistencies with the OData specification than that, especially the number parsing can be non-conformant.

**Comment by petrzjunior** [comment]
@lezsakdomi That's a good point I missed! You are correct as this is from the [grammar](https://github.com/oasis-tcs/odata-abnf/blob/main/abnf/odata-abnf-construction-rules.txt):
```abnf
stringLiteral    = SQUOTE *( SQUOTE-in-string / pchar-no-SQUOTE ) SQUOTE
SQUOTE-in-string = SQUOTE SQUOTE ; two consecutive single quotes represent one within a string literal
SQUOTE = "'" / "%27"
```
I thing that the most sane thing would be to make a breaking change and switch to single quotes to conform to the specification. This ensures that user would not be surprised by the behavior on a conforming input.

I initially created this project for my personal use but it is getting some traction on npm. I want this to remain a small implementation of a subset of OData. There are other projects which generate parser from the whole grammar, this is out of scope of this project. Still, I would be very much interested in improving conformace in the parts this library already covers.

I'll try to fix this in a few days. In case you find any more inconsistencies, feel free to report them, add tests or even open a PR.
